# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to heroku

on:
  push:
    branches: [ master ]

jobs:
  tag:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set pom
        run: mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }:1}
      
      - name: Commit files
        run: |
          git config --local user.email "s.celikce@gmail.com"
          git config --local user.name "Semih Çelik"
          git add ./pom.xml
          git commit -m "[ci] bump version"
          git push
          
  build:
    needs: tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package
      
    - name: Add heroku remote
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: Release
      run: git push heroku master
