name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      tag_to_publish:
        description: 'Tag version'
        default: 'v0.0.80'
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "semcelik/first-spring-project"
          version: ${{ github.event.inputs.tag_to_publish }}
          file: "*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
