name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      tag_to_publish:
        description: 'Tag version'
        default: 'v0.0.80'
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        env:
          TAG_NAME: ${{ github.event.inputs.tag_to_publish }}
        with:
          repo: "semcelik/first-spring-project"
          version: ${{ env.TAG_NAME }}
          file: demo-${TAG_NAME:1}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: ls
