name: Publish to Heroku

on: 
  workflow_dispatch:
    inputs:
      tag_to_publish:
        description: 'Tag to publish'     
        required: true


jobs:
  publish_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag_to_publish }}
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Get version
      run: echo "Preparing new build for version $(git describe --tags `git rev-list --tags --max-count=1`)"

    - name: Build with Maven
      run: mvn package
      
    - name: Add heroku remote
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: Release
      run: git push heroku origin/master:master

