name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_to_publish:
        description: 'Tag to publish (e.g: v0.0.1)'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.tag_to_publish }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag_to_publish }}
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: echo "Preparing new build for version ${{ env.TAG_NAME }}"

      - name: Build with Maven
        run: mvn package

      - name: Set APPLICATION_VERSION and JAR_FILE
        id: variables
        run: |
          echo "::set-output name=APPLICATION_VERSION::${{ env.TAG_NAME }}-$(date +%s)"
          echo "::set-output name=JAR_FILE::$(ls -R | grep -i "**.jar$")"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Upload ${{ steps.variables.outputs.JAR_FILE }} to S3 bucket
        run: aws s3 cp ./target/${{ steps.variables.outputs.JAR_FILE }} s3://${{ secrets.AWS_S3_BUCKET_NAME }}/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.AWS_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ secrets.AWS_S3_BUCKET_NAME }}",S3Key="${{ steps.variables.outputs.JAR_FILE }}" \
          --version-label "${{ steps.variables.outputs.APPLICATION_VERSION }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ secrets.AWS_ENVIRONMENT_NAME }} --version-label "${{ steps.variables.outputs.APPLICATION_VERSION }}"
