name: Publish

on: 
  workflow_dispatch:
    inputs:
      tag_to_publish:
        description: 'Tag to publish (e.g: v0.0.1)'     
        required: true


jobs:
  publish_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.tag_to_publish }}
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - run: echo "Preparing new build for version ${{ github.event.inputs.tag_to_publish }}"
      
    - name: Build with Maven
      run: mvn package
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-2"
        
    - name: Upload package to S3 bucket
      run: aws s3 cp ./target/$(ls -R | grep -i "**.jar$") s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
    
    - name: Create new ElasticBeanstalk Application Version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name spring-demo \
        --source-bundle S3Bucket="${{ secrets.AWS_S3_BUCKET_NAME }}",S3Key="./target/$(ls -R | grep -i "**.jar$")" \
        --version-label "ver-${{ github.sha }}" \
        --description "commit-sha-${{ github.sha }}"
         
         
    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name SpringDemo-env --version-label "ver-${{ github.sha }}"    
